apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::167468345794:role/eksctl-fsnd-nodegroup-ng-21a84370-NodeInstanceRole-1OI9HPPUANESP
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::167468345794:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-11-11T10:11:02Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "16781"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: 55530a65-a329-4f73-ab46-d16f0621bdf9
